-- liquibase formatted sql

--changeset IvanTyapkin:3
CREATE TABLE time_limit_exceed_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    method_signature VARCHAR(255),
    difference BIGINT,
    units_of_measurement VARCHAR(50)
);